### ISSUE TITLE
Crash on iOS 13.6.1

### ISSUE THREAD

**Issue by winest** [xuan32546/IOS13-SimulateTouch#25]
iPhone XR
iOS 13.6.1
JB with Odyssey, all unnecessary tweaks are disabled.
Work with 0.0.4 previously, but keep springboard crashing after upgraded to 0.0.6u4. Would it be possible to provide 0.0.4 deb binary again?

Always crashed if both "iOS Mouse-Keyboard Controller Debug" and "pccontrol.dylib" are enabled.

Two crash dump for reference:
[1.txt](https://github.com/xuan32546/IOS13-SimulateTouch/files/5859851/1.txt)
[2.txt](https://github.com/xuan32546/IOS13-SimulateTouch/files/5859852/2.txt)

**Comment by winest** [comment]
Updated: downgraded to 0.0.6 fix the issue. I don't know what's wrong with 0.0.6u4

**Comment by xuan32546** [comment]
fixed. Try 0.0.6-8

**Comment by winest** [comment]
Still reproducible on latest 0.0.7u2
So I downgrade to each version one by one, 
and find this crash happen since 0.0.6u1
(0.0.6 is fine to use, but 0.0.6u1 will always crash)

2 logs from 0.0.6u1 for reference:
[Log1.txt](https://github.com/xuan32546/IOS13-SimulateTouch/files/5941275/Log1.txt)
[Log2.txt](https://github.com/xuan32546/IOS13-SimulateTouch/files/5941277/Log2.txt)
